[tool.poetry]
name = "cosmicpython"
version = "0.1.0"
description = ""
authors = ["Alexus Wong <awong@aledade.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.3.5"
invoke = "^2.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
addopts = "-vs"
